get_countries:
  target:
    entity:
      integration: wine_cellar
get_inventory:
  target:
    entity:
      integration: wine_cellar
refresh_inventory:
  target:
    entity:
      integration: wine_cellar
